name = "jira-to-miro"
main = "src/index.js"
compatibility_date = "2026-08-24"
keep_vars = true

[observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "CARD_MAP"
id = "6c0c1018f7f940bbaaef6bc0bca76f47"
