name = "jira-to-miro-refactor-test"
main = "src/index.js"
compatibility_date = "2026-09-01"
keep_vars = true
preview_urls = false

[vars]
JIRA_CLOUD_ID = "9e93c25f-4279-40a5-8076-732017184ac4"
MIRO_BOARD_ID = "uXjVP6-u9TE="

[observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "CARD_MAP"
id = "a30e97dd100c4b8b99dcda316133c51b"
