import { config } from './config.js';
import { text } from './auth.js';

export function renderAppClient(env) {
  const cfg = config(env);
  const script = String.raw`(async function(){
const layout=${JSON.stringify(cfg.layout)},threshold=${cfg.overlapThreshold},jiraSiteUrl=${JSON.stringify(cfg.jiraSiteUrl)};
const timers=new Map(),baselines=new Map(),rollbacks=new Map(),reconciliationBlocked=new Map(),customKnown=new Map();
const norm=v=>String(v||'').trim().toUpperCase();
const itemTitle=item=>String(item&&((item.data&&item.data.title)||item.title||item.name)||'').trim();const imageKey=item=>{const m=itemTitle(item).match(/^CUSTOM_JIRA_CARD:\s*(${cfg.jiraProjectKey}-\d+)$/i);return m?norm(m[1]):null};const commentKey=item=>{const m=itemTitle(item).match(/^JIRA_COMMENT_INDICATOR:\s*(${cfg.jiraProjectKey}-\d+)$/i);return m?norm(m[1]):null};
const snapshot=item=>{if(!item||item.type!=='image')return null;const key=imageKey(item);return key?{item,key,x:Number(item.x),y:Number(item.y),width:Number(item.width)||1}:null};
const remember=s=>{if(s&&Number.isFinite(s.x)&&Number.isFinite(s.y))baselines.set(String(s.item.id),{previousX:s.x,previousY:s.y})};
const inside=(x,y)=>Number.isFinite(x)&&Number.isFinite(y)&&x>=layout.board.left&&x<=layout.board.right&&y>=layout.board.top&&y<=layout.board.bottom;
async function canvasPosition(item,seen=new Set()){if(!item)return null;const id=String(item.id||'');if(id&&seen.has(id))return null;if(id)seen.add(id);const x=Number(item.x),y=Number(item.y);if(!Number.isFinite(x)||!Number.isFinite(y))return null;const parentId=String(item.parentId||'').trim(),relative=String(item.relativeTo||'canvas_center');if(!parentId||relative==='canvas_center')return{x,y};const parent=await miro.board.getById(parentId);if(!parent)return null;const p=await canvasPosition(parent,seen);if(!p)return null;if(relative==='parent_center')return{x:p.x+x,y:p.y+y};if(relative==='parent_top_left'){const w=Number(parent.width),h=Number(parent.height);return Number.isFinite(w)&&Number.isFinite(h)?{x:p.x-w/2+x,y:p.y-h/2+y}:null}return null}
async function boardPosition(s){const item=s.item,x=s.x,y=s.y;if(!Number.isFinite(x)||!Number.isFinite(y))return null;const parentId=String(item&&item.parentId||'').trim(),relative=String(item&&item.relativeTo||'canvas_center');if(parentId&&relative.indexOf('parent_')===0){const parent=await miro.board.getById(parentId);const w=Number(parent&&parent.width),h=Number(parent&&parent.height);if(parent&&Number.isFinite(w)&&Number.isFinite(h)&&w>=layout.board.right&&h>=layout.board.bottom&&inside(x,y))return{x,y}}const canvas=await canvasPosition(item);if(!canvas)return null;if(inside(canvas.x,canvas.y))return canvas;const frames=await miro.board.get({type:'frame'});const candidates=(frames||[]).map(frame=>{const fx=Number(frame.x),fy=Number(frame.y),w=Number(frame.width),h=Number(frame.height);if(![fx,fy,w,h].every(Number.isFinite)||w<layout.board.right||h<layout.board.bottom)return null;const left=fx-w/2,top=fy-h/2,lx=canvas.x-left,ly=canvas.y-top;return inside(lx,ly)?{x:lx,y:ly,area:w*h}:null}).filter(Boolean).sort((a,b)=>a.area-b.area);return candidates[0]||null}
async function column(s){const pos=await boardPosition(s);if(!pos)return null;const w=s.width||1,l=pos.x-w/2,r=pos.x+w/2;return layout.columns.map(c=>({...c,ratio:Math.max(0,Math.min(r,c.right)-Math.max(l,c.left))/w})).sort((a,b)=>b.ratio-a.ratio)[0]}
async function post(path,body){const token=await miro.board.getIdToken();return fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)})}
async function ensureLink(item,key){try{const expected=jiraSiteUrl+'/browse/'+key;if(String(item.linkedTo||'')===expected)return;item.linkedTo=expected;await item.sync()}catch(e){console.error('Could not restore Jira link',key,e)}}
let lastCommentModalKey='',lastCommentModalAt=0;
async function openComments(item,key){const now=Date.now();if(lastCommentModalKey===key&&now-lastCommentModalAt<1200)return;lastCommentModalKey=key;lastCommentModalAt=now;try{if(!(await miro.board.ui.canOpenModal()))return;const cards=await miro.board.get({type:'image'});const card=cards.find(candidate=>imageKey(candidate)===key);if(!card){console.warn('No custom card found for Jira comment indicator',key);return}await miro.board.ui.openModal({url:'/jira-comments-modal',data:{issueKey:key,itemId:String(card.id)},width:760,height:800,fullscreen:false})}catch(e){console.error('Could not open Jira comments',e)}}
async function openCommentMenu(item,key){try{if(!(await miro.board.ui.canOpenModal()))return;const cards=await miro.board.get({type:'image'});const card=cards.find(candidate=>imageKey(candidate)===key);if(!card)return;await miro.board.ui.openModal({url:'/jira-card-menu',data:{issueKey:key,itemId:String(card.id)},width:760,height:800,fullscreen:false})}catch(error){console.error('Could not open Jira card menu',error)}}
async function syncIndicatorPosition(card,key){try{const width=Number(card&&card.width),height=Number(card&&card.height),x=Number(card&&card.x),y=Number(card&&card.y);if(![width,height,x,y].every(Number.isFinite))return;const indicators=await miro.board.get({type:'image'});const indicator=(indicators||[]).find(candidate=>commentKey(candidate)===key);if(!indicator)return;const nextX=x+width/2-25,nextY=y-height/2+22;if(Math.abs(Number(indicator.x)-nextX)<1&&Math.abs(Number(indicator.y)-nextY)<1)return;indicator.x=nextX;indicator.y=nextY;await indicator.sync()}catch(error){console.error('Could not move Jira comment indicator with card',error)}}
async function detachDuplicate(item,key){const id=String(item&&item.id||'').trim(),original=customKnown.get(key);if(!original||!id||original===id)return false;try{const title='Miro copy – '+key;if(item.data&&typeof item.data==='object')item.data.title=title;item.title=title;await item.sync();console.log('Detached copied Jira card while keeping Jira link',key,id);return true}catch(e){console.error('Could not detach copied Jira card',key,e);return false}}
async function register(){const info=await miro.board.getInfo(),custom=[],all=[];for(const item of await miro.board.get({type:'image'})||[]){const accidental=String(itemTitle(item)).match(/^Miro copy – (${cfg.jiraProjectKey}-\d+)$/i);if(accidental){const restored='CUSTOM_JIRA_CARD:'+norm(accidental[1]);if(item.data&&typeof item.data==='object')item.data.title=restored;item.title=restored;await item.sync().catch(()=>{})}const s=snapshot(item);if(!s)continue;if((reconciliationBlocked.get(s.key)||0)<=Date.now())all.push({issueKey:s.key,itemId:String(item.id)});await ensureLink(item,s.key);const id=String(item.id);if(!baselines.has(id))remember(s);if(customKnown.get(s.key)!==id){custom.push({issueKey:s.key,itemId:id});customKnown.set(s.key,id)}}if(custom.length)await post('/register-custom-cards',{boardId:info.id,cards:custom});if(all.length)await post('/reconcile-custom-cards',{boardId:info.id,cards:all.slice(0,100)})}
async function rollback(s,original){if(!original||!Number.isFinite(original.previousX)||!Number.isFinite(original.previousY))return false;try{const current=await miro.board.getById(String(s.item.id));if(!current)return false;rollbacks.set(String(s.item.id),Date.now()+5000);reconciliationBlocked.set(s.key,Date.now()+5000);current.x=original.previousX;current.y=original.previousY;await current.sync();const after=snapshot(current);if(after)remember(after);return true}catch(e){console.error('Rollback failed',e);return false}}
function jiraFailureDetail(detail){const raw=String(detail||'').trim();let parsed=null;try{parsed=JSON.parse(raw)}catch{}const messages=[];if(Array.isArray(parsed?.errorMessages))messages.push(...parsed.errorMessages);if(parsed?.errors&&typeof parsed.errors==='object')messages.push(...Object.entries(parsed.errors).map(([field,message])=>String(message||field)));const text=messages.map(value=>String(value).replace(/\s+/g,' ').trim()).find(Boolean)||raw.replace(/\s+/g,' ').trim();const completed=text.match(/^(.+?)\s+must be completed\b/i);if(completed){const fields=completed[1].trim();return fields.includes(' and ')?fields+' are missing.':fields+' is missing.'}const required=text.match(/^(.+?)\s+(?:is|was)\s+required\.?$/i)||text.match(/^(.+?)\s+(?:is|was)\s+missing\.?$/i);return required?'Required field '+required[1]+' is missing.':text}
async function showStatusFailure(second,target,original,detail){const ok=await rollback(second,original);const reason=jiraFailureDetail(detail);const message=(reason||'Required field is missing.').slice(0,80);try{await miro.board.notifications.showError(message)}catch(e){console.error('Could not show status error in Miro',e)}}
async function evaluate(id,original){const firstItem=await miro.board.getById(id),first=snapshot(firstItem);if(!first)return;await new Promise(r=>setTimeout(r,300));const item=await miro.board.getById(id),second=snapshot(item);if(!second)return;if(Math.abs(second.x-first.x)>1||Math.abs(second.y-first.y)>1)return;const target=await column(second);if(!target||target.ratio<threshold){remember(second);return}reconciliationBlocked.set(second.key,Date.now()+5000);const info=await miro.board.getInfo(),body={boardId:info.id,issueKey:second.key,itemId:id,desiredStatus:target.status};let response,result;try{response=await post('/custom-miro-to-jira',body);result=await response.json()}catch(e){console.error('Status sync failed',e);await showStatusFailure(second,target,original,'The status request could not be completed.');return}if(!response.ok||result&&result.ok===false){const detail=result&&((result.error&&String(result.error))||(result.reason&&String(result.reason)));await showStatusFailure(second,target,original,detail);return}remember(second)}
async function resolveCommentKey(item){const direct=commentKey(item);if(direct)return direct;if(!item||item.type!=='image')return null;const w=Number(item.width),h=Number(item.height);if(![w,h].every(Number.isFinite)||w>80||h>60)return null;const images=await miro.board.get({type:'image'});let best=null,bestDistance=Infinity;for(const candidate of images||[]){const key=imageKey(candidate);if(!key)continue;const dx=Math.abs(Number(candidate.x)-Number(item.x)),dy=Math.abs(Number(candidate.y)-Number(item.y));const distance=dx+dy;if(dx<=80&&dy<=80&&distance<bestDistance){best=key;bestDistance=distance}}return best}
async function groupCommentKey(group){try{const items=await group.getItems();const card=(items||[]).find(item=>imageKey(item));return card?{key:imageKey(card),item:card}:null}catch(error){console.error('Could not inspect Jira comment group',error);return null}}
let groupSelectionTimer=null;
function clearGroupSelectionTimer(){if(groupSelectionTimer){clearTimeout(groupSelectionTimer);groupSelectionTimer=null}}

let followTimer=null;
function stopIndicatorFollow(){if(followTimer){clearInterval(followTimer);followTimer=null}}
function followIndicator(item,key){stopIndicatorFollow();const id=String(item&&item.id||'');if(!id||!key)return;followTimer=setInterval(async()=>{try{const current=await miro.board.getById(id);if(current)await syncIndicatorPosition(current,key)}catch(error){console.error('Could not follow Jira comment indicator',error)}},300)}
async function itemsUpdated(event){const items=event&&event.items||[],candidates=new Set();for(const item of items){const id=String(item&&item.id||'').trim();if(!id)continue;const s=snapshot(item);if(s){await syncIndicatorPosition(item,s.key)}if(item.type==='image'||[...customKnown.values()].includes(id))candidates.add(id);else if(item.parentId&&[...customKnown.values()].includes(String(item.parentId)))candidates.add(String(item.parentId))}for(const id of candidates){const until=rollbacks.get(id)||0;if(until>Date.now()){rollbacks.delete(id);continue}const old=timers.get(id);if(old)clearTimeout(old.timer);const original=(old&&old.original)||baselines.get(id)||null;const timer=setTimeout(()=>{timers.delete(id);evaluate(id,original).catch(console.error)},1200);timers.set(id,{timer,original})}}
async function itemsCreated(event){const items=event&&event.items||[],info=await miro.board.getInfo(),custom=[];for(const item of items){const accidental=String(itemTitle(item)).match(/^Miro copy – (${cfg.jiraProjectKey}-\d+)$/i);if(accidental){const restored='CUSTOM_JIRA_CARD:'+norm(accidental[1]);if(item.data&&typeof item.data==='object')item.data.title=restored;item.title=restored;await item.sync().catch(()=>{})}const s=snapshot(item);if(!s)continue;await ensureLink(item,s.key);const id=String(item.id);if(!baselines.has(id))remember(s);if(customKnown.get(s.key)!==id){customKnown.set(s.key,id);custom.push({issueKey:s.key,itemId:id})}}if(custom.length)await post('/register-custom-cards',{boardId:info.id,cards:custom})}
let linkScanTimer=null;
function startLinkScan(){if(linkScanTimer)return;const tick=async()=>{try{await register()}catch(error){console.error('Link registration scan failed',error)}linkScanTimer=setTimeout(tick,10000)};tick()}
async function bindItemUpdates(){const bindings=[[miro.board.ui,'experimental:items:update'],[miro.board.experimental,'experimental:items:update'],[miro.board.ui,'items:update'],[miro.board.experimental,'items:update']];for(const [scope,eventName] of bindings){try{if(scope&&typeof scope.on==='function')await scope.on(eventName,itemsUpdated)}catch(error){console.warn('Could not bind Miro item update event',eventName,error)}}}
await miro.board.ui.on('icon:click',async()=>{try{startLinkScan();if(await miro.board.ui.canOpenPanel())await miro.board.ui.openPanel({url:'/miro-panel'})}catch(e){console.error(e)}});
await miro.board.ui.on('selection:update',async event=>{clearGroupSelectionTimer();const selected=event&&event.items||await miro.board.getSelection();const raw=Array.isArray(selected)&&selected.length===1?selected[0]:null;const item=raw&&raw.id?await miro.board.getById(String(raw.id)):raw;const selectedCard=snapshot(item);if(selectedCard&&!timers.has(String(selectedCard.item.id))&&!rollbacks.has(String(selectedCard.item.id)))remember(selectedCard);if(item&&item.type==='group'){const group=item;const found=await groupCommentKey(group);if(found){const startX=Number(group.x),startY=Number(group.y);groupSelectionTimer=setTimeout(async()=>{groupSelectionTimer=null;try{const current=await miro.board.getById(String(group.id));if(current&&Math.abs(Number(current.x)-startX)<2&&Math.abs(Number(current.y)-startY)<2)await openCommentMenu(found.item,found.key)}catch(error){console.error('Could not open group comments',error)}},350)}stopIndicatorFollow();return}const comment=await resolveCommentKey(item);if(comment){stopIndicatorFollow();await openComments(item,comment);return}const card=imageKey(item);if(card){followIndicator(item,card);const cardId=String(item.id||''),startX=Number(item.x),startY=Number(item.y);groupSelectionTimer=setTimeout(async()=>{groupSelectionTimer=null;try{const current=await miro.board.getById(cardId);if(current&&Math.abs(Number(current.x)-startX)<2&&Math.abs(Number(current.y)-startY)<2)await openCommentMenu(current,card)}catch(error){console.error('Could not open Jira card menu',error)}},350);return}stopIndicatorFollow()});
await miro.board.ui.on('items:create',async event=>{startLinkScan();await itemsCreated(event)});
await bindItemUpdates();
startLinkScan();
console.log('Jira/Miro SVG custom-card sync app ready');
})();`;
  return text(script, 'application/javascript; charset=utf-8');
}
