import { config } from './config.js';
import { text } from './auth.js';

export function renderAppClient(env) {
  const cfg = config(env);
  const script = String.raw`(async function(){
const layout=${JSON.stringify(cfg.layout)},threshold=${cfg.overlapThreshold},jiraSiteUrl=${JSON.stringify(cfg.jiraSiteUrl)};
const timers=new Map(),baselines=new Map(),rollbacks=new Map(),customKnown=new Map();
const norm=v=>String(v||'').trim().toUpperCase();
const itemTitle=item=>String(item&&((item.data&&item.data.title)||item.title||item.name)||'').trim();const imageKey=item=>{const m=itemTitle(item).match(/^CUSTOM_JIRA_CARD:\s*(${cfg.jiraProjectKey}-\d+)$/i);return m?norm(m[1]):null};const commentKey=item=>{const m=itemTitle(item).match(/^JIRA_COMMENT_INDICATOR:\s*(${cfg.jiraProjectKey}-\d+)$/i);return m?norm(m[1]):null};
const snapshot=item=>{if(!item||item.type!=='image')return null;const key=imageKey(item);return key?{item,key,x:Number(item.x),y:Number(item.y),width:Number(item.width)||1}:null};
const remember=s=>{if(s&&Number.isFinite(s.x)&&Number.isFinite(s.y))baselines.set(String(s.item.id),{x:s.x,y:s.y})};
const inside=(x,y)=>Number.isFinite(x)&&Number.isFinite(y)&&x>=layout.board.left&&x<=layout.board.right&&y>=layout.board.top&&y<=layout.board.bottom;
async function canvasPosition(item,seen=new Set()){if(!item)return null;const id=String(item.id||'');if(id&&seen.has(id))return null;if(id)seen.add(id);const x=Number(item.x),y=Number(item.y);if(!Number.isFinite(x)||!Number.isFinite(y))return null;const parentId=String(item.parentId||'').trim(),relative=String(item.relativeTo||'canvas_center');if(!parentId||relative==='canvas_center')return{x,y};const parent=await miro.board.getById(parentId);if(!parent)return null;const p=await canvasPosition(parent,seen);if(!p)return null;if(relative==='parent_center')return{x:p.x+x,y:p.y+y};if(relative==='parent_top_left'){const w=Number(parent.width),h=Number(parent.height);return Number.isFinite(w)&&Number.isFinite(h)?{x:p.x-w/2+x,y:p.y-h/2+y}:null}return null}
async function boardPosition(s){const item=s.item,x=s.x,y=s.y;if(!Number.isFinite(x)||!Number.isFinite(y))return null;const parentId=String(item&&item.parentId||'').trim(),relative=String(item&&item.relativeTo||'canvas_center');if(parentId&&relative.indexOf('parent_')===0){const parent=await miro.board.getById(parentId);const w=Number(parent&&parent.width),h=Number(parent&&parent.height);if(parent&&Number.isFinite(w)&&Number.isFinite(h)&&w>=layout.board.right&&h>=layout.board.bottom&&inside(x,y))return{x,y}}const canvas=await canvasPosition(item);if(!canvas)return null;if(inside(canvas.x,canvas.y))return canvas;const frames=await miro.board.get({type:'frame'});const candidates=(frames||[]).map(frame=>{const fx=Number(frame.x),fy=Number(frame.y),w=Number(frame.width),h=Number(frame.height);if(![fx,fy,w,h].every(Number.isFinite)||w<layout.board.right||h<layout.board.bottom)return null;const left=fx-w/2,top=fy-h/2,lx=canvas.x-left,ly=canvas.y-top;return inside(lx,ly)?{x:lx,y:ly,area:w*h}:null}).filter(Boolean).sort((a,b)=>a.area-b.area);return candidates[0]||null}
async function column(s){const pos=await boardPosition(s);if(!pos)return null;const w=s.width||1,l=pos.x-w/2,r=pos.x+w/2;return layout.columns.map(c=>({...c,ratio:Math.max(0,Math.min(r,c.right)-Math.max(l,c.left))/w})).sort((a,b)=>b.ratio-a.ratio)[0]}
async function post(path,body){const token=await miro.board.getIdToken();return fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)})}
async function ensureLink(item,key){const link=jiraSiteUrl+'/browse/'+key;if(item.linkedTo===link)return;try{item.linkedTo=link;await item.sync()}catch(e){console.error('Could not link Jira card',key,e)}}
let lastCommentModalKey='',lastCommentModalAt=0;
async function openComments(item,key){const now=Date.now();if(lastCommentModalKey===key&&now-lastCommentModalAt<1200)return;lastCommentModalKey=key;lastCommentModalAt=now;try{if(!(await miro.board.ui.canOpenModal()))return;const cards=await miro.board.get({type:'image'});const card=cards.find(candidate=>imageKey(candidate)===key);if(!card){console.warn('No custom card found for Jira comment indicator',key);return}await miro.board.ui.openModal({url:'/jira-comments-modal',data:{issueKey:key,itemId:String(card.id)},width:560,height:700,fullscreen:false})}catch(e){console.error('Could not open Jira comments',e)}}
async function syncIndicatorPosition(card,key){try{const width=Number(card&&card.width),height=Number(card&&card.height),x=Number(card&&card.x),y=Number(card&&card.y);if(![width,height,x,y].every(Number.isFinite))return;const indicators=await miro.board.get({type:'image'});const indicator=(indicators||[]).find(candidate=>commentKey(candidate)===key);if(!indicator)return;const nextX=x+width/2-25,nextY=y-height/2+22;if(Math.abs(Number(indicator.x)-nextX)<1&&Math.abs(Number(indicator.y)-nextY)<1)return;indicator.x=nextX;indicator.y=nextY;await indicator.sync()}catch(error){console.error('Could not move Jira comment indicator with card',error)}}
async function detachDuplicate(item,key){const id=String(item&&item.id||'').trim(),original=customKnown.get(key);if(!original||!id||original===id)return false;try{const title='Miro copy – '+key;if(item.data&&typeof item.data==='object')item.data.title=title;item.title=title;await item.sync();console.log('Detached copied Jira card while keeping Jira link',key,id);return true}catch(e){console.error('Could not detach copied Jira card',key,e);return false}}
async function register(){const info=await miro.board.getInfo(),custom=[];for(const item of await miro.board.get({type:'image'})||[]){const s=snapshot(item);if(!s)continue;await ensureLink(item,s.key);const id=String(item.id);if(!baselines.has(id))remember(s);if(customKnown.get(s.key)!==id){custom.push({issueKey:s.key,itemId:id});customKnown.set(s.key,id)}}if(custom.length)await post('/register-custom-cards',{boardId:info.id,cards:custom})}
async function rollback(s,original){if(!original)return false;try{const current=await miro.board.getById(String(s.item.id));if(!current)return false;rollbacks.set(String(s.item.id),Date.now()+5000);current.x=original.x;current.y=original.y;await current.sync();const after=snapshot(current);if(after)remember(after);return true}catch(e){console.error('Rollback failed',e);return false}}
async function evaluate(id,original){const firstItem=await miro.board.getById(id),first=snapshot(firstItem);if(!first)return;await new Promise(r=>setTimeout(r,300));const item=await miro.board.getById(id),second=snapshot(item);if(!second)return;if(Math.abs(second.x-first.x)>1||Math.abs(second.y-first.y)>1)return;const target=await column(second);if(!target||target.ratio<threshold){remember(second);return}const info=await miro.board.getInfo(),body={boardId:info.id,issueKey:second.key,itemId:id,desiredStatus:target.status};let response,result;try{response=await post('/custom-miro-to-jira',body);result=await response.json()}catch(e){console.error('Status sync failed',e);return}if(!response.ok||result&&result.ok===false){const ok=await rollback(second,original),message=result&&result.reason==='TEST_AREA_REQUIRED'?'Test area must be filled in before moving to Functional review.':second.key+' could not be moved to '+target.status+'. Jira rejected the status change.'+(ok?'':' Miro rollback also failed.');try{await miro.board.notifications.showError(message)}catch{}return}remember(second)}
async function resolveCommentKey(item){const direct=commentKey(item);if(direct)return direct;if(!item||item.type!=='image')return null;const w=Number(item.width),h=Number(item.height);if(![w,h].every(Number.isFinite)||w>80||h>60)return null;const images=await miro.board.get({type:'image'});let best=null,bestDistance=Infinity;for(const candidate of images||[]){const key=imageKey(candidate);if(!key)continue;const dx=Math.abs(Number(candidate.x)-Number(item.x)),dy=Math.abs(Number(candidate.y)-Number(item.y));const distance=dx+dy;if(dx<=80&&dy<=80&&distance<bestDistance){best=key;bestDistance=distance}}return best}
let indicatorTracker=null;
function isSmallIndicator(item){const w=Number(item&&item.width),h=Number(item&&item.height);return Number.isFinite(w)&&Number.isFinite(h)&&w<=80&&h<=60}
async function trackAllIndicators(){try{const images=await miro.board.get({type:'image'});const cards=(images||[]).filter(item=>imageKey(item));for(const card of cards){const key=imageKey(card);let indicator=(images||[]).find(item=>commentKey(item)===key);if(!indicator)indicator=(images||[]).filter(isSmallIndicator).sort((a,b)=>{const da=Math.abs(Number(a.x)-(Number(card.x)+Number(card.width)/2-25))+Math.abs(Number(a.y)-(Number(card.y)-Number(card.height)/2+22));const db=Math.abs(Number(b.x)-(Number(card.x)+Number(card.width)/2-25))+Math.abs(Number(b.y)-(Number(card.y)-Number(card.height)/2+22));return da-db})[0];if(!indicator)continue;const x=Number(card.x)+Number(card.width)/2-25,y=Number(card.y)-Number(card.height)/2+22;if(Math.abs(Number(indicator.x)-x)>1||Math.abs(Number(indicator.y)-y)>1){indicator.x=x;indicator.y=y;await indicator.sync()}}}catch(error){console.error('Comment indicator tracker failed',error)}}
function startIndicatorTracker(){if(indicatorTracker)return;indicatorTracker=setInterval(trackAllIndicators,400);trackAllIndicators()}
let followTimer=null;
function stopIndicatorFollow(){if(followTimer){clearInterval(followTimer);followTimer=null}}
function followIndicator(item,key){stopIndicatorFollow();const id=String(item&&item.id||'');if(!id||!key)return;followTimer=setInterval(async()=>{try{const current=await miro.board.getById(id);if(current)await syncIndicatorPosition(current,key)}catch(error){console.error('Could not follow Jira comment indicator',error)}},300)}
async function itemsUpdated(event){const items=event&&event.items||[],candidates=new Set();for(const item of items){const id=String(item&&item.id||'').trim();if(!id)continue;const s=snapshot(item);if(s){await syncIndicatorPosition(item,s.key);if(await detachDuplicate(item,s.key))continue}if(item.type==='image'||[...customKnown.values()].includes(id))candidates.add(id);else if(item.parentId&&[...customKnown.values()].includes(String(item.parentId)))candidates.add(String(item.parentId))}for(const id of candidates){const until=rollbacks.get(id)||0;if(until>Date.now()){rollbacks.delete(id);continue}const old=timers.get(id);if(old)clearTimeout(old.timer);const eventItem=items.find(item=>String(item&&item.id||'')===id);const original=baselines.get(id)||(old&&old.original)||(eventItem?{x:Number(eventItem.x),y:Number(eventItem.y)}:null);const timer=setTimeout(()=>{timers.delete(id);evaluate(id,original).catch(console.error)},1200);timers.set(id,{timer,original})}}
async function itemsCreated(event){const items=event&&event.items||[],info=await miro.board.getInfo(),custom=[];for(const item of items){const s=snapshot(item);if(!s)continue;if(await detachDuplicate(item,s.key))continue;await ensureLink(item,s.key);const id=String(item.id);if(!baselines.has(id))remember(s);if(customKnown.get(s.key)!==id){customKnown.set(s.key,id);custom.push({issueKey:s.key,itemId:id})}}if(custom.length)await post('/register-custom-cards',{boardId:info.id,cards:custom})}
let linkScanTimer=null;
function startLinkScan(){if(linkScanTimer)return;const tick=async()=>{try{await register()}catch(error){console.error('Link registration scan failed',error)}linkScanTimer=setTimeout(tick,10000)};tick()}
await miro.board.ui.on('icon:click',async()=>{try{startLinkScan();if(await miro.board.ui.canOpenPanel())await miro.board.ui.openPanel({url:'/miro-panel'})}catch(e){console.error(e)}});
await miro.board.ui.on('selection:update',async event=>{const selected=event&&event.items||await miro.board.getSelection();const raw=Array.isArray(selected)&&selected.length===1?selected[0]:null;const item=raw&&raw.id?await miro.board.getById(String(raw.id)):raw;const comment=await resolveCommentKey(item);if(comment){stopIndicatorFollow();await openComments(item,comment);return}const card=imageKey(item);if(card){followIndicator(item,card);return}stopIndicatorFollow()});
await miro.board.ui.on('items:create',async event=>{startLinkScan();await itemsCreated(event)});
await miro.board.ui.on('experimental:items:update',itemsUpdated);try{await miro.board.ui.on('items:update',itemsUpdated)}catch{}
startLinkScan();startIndicatorTracker();
console.log('Jira/Miro SVG custom-card sync app ready');
})();`;
  return text(script, 'application/javascript; charset=utf-8');
}