import { config } from './config.js';
import { text } from './auth.js';

export function renderPanelClient(env) {
  const cfg = config(env);
  const script = String.raw`(function(){
const META='rendraStickyJiraConversionV1',layout=${JSON.stringify(cfg.layout)},threshold=${cfg.overlapThreshold};
const colorMap={light_pink:'Bug',pink:'Bug',violet:'Bug',light_blue:'Improvement',blue:'Improvement',dark_blue:'Improvement',gray:'Improvement',light_yellow:'Spike',yellow:'Spike',light_green:'New Feature',green:'New Feature',dark_green:'New Feature',orange:'Hotfix candidate',red:'Hotfix candidate',cyan:'Task/config/doc/test'};
const button=document.getElementById('convertButton'),statusEl=document.getElementById('status');
const status=(m,t='info')=>{statusEl.className=t;statusEl.textContent=m};
const plain=v=>{const d=document.createElement('div');d.innerHTML=String(v||'');return String(d.textContent||'').replace(/\s+/g,' ').trim()};
const creator=v=>!v?'':typeof v==='string'||typeof v==='number'?String(v).trim():String(v.id||v.userId||v.memberId||v.user&&v.user.id||'').trim();
async function post(path,body){const token=await miro.board.getIdToken();return fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)})}
async function canvas(item){const x=Number(item&&item.x),y=Number(item&&item.y);if(!Number.isFinite(x)||!Number.isFinite(y))throw new Error('A selected note has an invalid board position.');if(!item.parentId||item.relativeTo==='canvas_center')return{x,y};const parent=await miro.board.getById(item.parentId);if(!parent)throw new Error("Could not resolve a selected note's parent frame.");const p=await canvas(parent);if(item.relativeTo==='parent_top_left'){const w=Number(parent.width),h=Number(parent.height);if(!Number.isFinite(w)||!Number.isFinite(h))throw new Error("Could not resolve a selected note's frame dimensions.");return{x:p.x-w/2+x,y:p.y-h/2+y}}if(item.relativeTo==='parent_center')return{x:p.x+x,y:p.y+y};return{x,y}}
async function workflowPosition(item,pos){if(item.parentId&&String(item.relativeTo||'').indexOf('parent_')===0){const parent=await miro.board.getById(item.parentId),w=Number(parent&&parent.width),h=Number(parent&&parent.height);if(parent&&Number.isFinite(w)&&Number.isFinite(h)&&w>=layout.board.right&&h>=layout.board.bottom){const x=Number(item.x),y=Number(item.y);if(Number.isFinite(x)&&Number.isFinite(y))return{x,y}}}const frames=await miro.board.get({type:'frame'}),candidates=(frames||[]).map(frame=>{const fx=Number(frame.x),fy=Number(frame.y),w=Number(frame.width),h=Number(frame.height);if(![fx,fy,w,h].every(Number.isFinite)||w<layout.board.right||h<layout.board.bottom)return null;const left=fx-w/2,top=fy-h/2,x=pos.x-left,y=pos.y-top;return x>=layout.board.left&&x<=layout.board.right&&y>=layout.board.top&&y<=layout.board.bottom?{x,y,area:w*h}:null}).filter(Boolean).sort((a,b)=>a.area-b.area);return candidates[0]||null}
async function desired(sticky,pos){const local=await workflowPosition(sticky,pos);if(!local)return null;const w=Number(sticky.width)||1,l=local.x-w/2,r=local.x+w/2;const best=layout.columns.map(c=>({status:c.status,ratio:Math.max(0,Math.min(r,c.right)-Math.max(l,c.left))/w})).sort((a,b)=>b.ratio-a.ratio)[0];return best&&best.ratio>=threshold?best.status:null}
async function jsonResult(response,fallback){let result=null;try{result=await response.json()}catch{}if(!response.ok||!result||!result.ok){const detail=result&&(result.reason||result.error);throw new Error(typeof detail==='string'&&detail?detail:fallback)}return result}
async function removeConvertedSticky(sticky){const id=String(sticky&&sticky.id||'').trim();if(!id)throw new Error('Converted sticky has no Miro item ID.');for(let attempt=0;attempt<2;attempt++){let current=null;try{current=await miro.board.getById(id)}catch{}if(!current)return;try{await miro.board.remove(current)}catch(e){if(attempt===1)throw e}await new Promise(r=>setTimeout(r,150))}let remaining=null;try{remaining=await miro.board.getById(id)}catch{}if(remaining)throw new Error('Jira card was created, but the original sticky could not be removed.')}
async function convert(sticky){const summary=plain(sticky.content);if(!summary)throw new Error('This sticky note has no text.');const pos=await canvas(sticky),want=await desired(sticky,pos),workType=colorMap[String(sticky&&sticky.style&&sticky.style.fillColor||'').trim().toLowerCase()]||'Bug',stickyColor=String(sticky&&sticky.style&&sticky.style.fillColor||'');let state;try{state=await sticky.getMetadata(META)}catch{}let issueKey=state&&state.issueKey?String(state.issueKey):'';if(!issueKey){const created=await jsonResult(await post('/sticky-to-jira',{summary,workType,stickyId:String(sticky.id),createdBy:creator(sticky.createdBy)}),'Could not create Jira issue.');issueKey=String(created.issueKey);await sticky.setMetadata(META,{issueKey,stage:'jira-created',workType,stickyColor,desiredStatus:want||null})}if(want)await jsonResult(await post('/conversion-set-status',{issueKey,desiredStatus:want}),'Could not set Jira status.');const card=await jsonResult(await post('/conversion-direct-card',{issueKey,x:pos.x,y:pos.y}),'Could not create Miro card at the note position.');await sticky.setMetadata(META,{issueKey,stage:'card-created',customCardFrameId:String(card.itemId),workType,stickyColor,desiredStatus:want||null});await removeConvertedSticky(sticky);return{issueKey,desiredStatus:want}}
button.addEventListener('click',async()=>{button.disabled=true;try{const selected=await miro.board.getSelection(),items=Array.isArray(selected)?selected:[],stickies=items.filter(i=>i&&i.type==='sticky_note');if(!stickies.length)throw new Error('Select at least one sticky note first.');if(stickies.length!==items.length)throw new Error('Select only sticky notes before converting.');const ok=[],fail=[];for(let i=0;i<stickies.length;i++){status('Converting '+(i+1)+' of '+stickies.length+'...');try{ok.push(await convert(stickies[i]))}catch(e){fail.push({text:plain(stickies[i].content).slice(0,60)||'Untitled note',reason:e&&e.message||String(e)})}}if(!fail.length)status(ok.length===1?ok[0].issueKey+' converted successfully.':ok.length+' notes converted successfully.','success');else if(ok.length)status(ok.length+' converted successfully. '+fail.length+' failed and were left on the board.\n\n'+fail.map(x=>x.text+': '+x.reason).join('\n'),'error');else status('No notes were converted.\n\n'+fail.map(x=>x.text+': '+x.reason).join('\n'),'error')}catch(e){status(e&&e.message||String(e),'error')}finally{button.disabled=false}});
document.getElementById('creatorIdButton').addEventListener('click',async()=>{const s=await miro.board.getSelection();if(!Array.isArray(s)||s.length!==1)return alert('Select exactly one item first.');const value=creator(s[0].createdBy);if(!value)return alert('Could not read creator ID for the selected item.');document.getElementById('creatorId').value=value;document.getElementById('creatorDiagnostic').style.display='block'});
document.getElementById('frameIdButton').addEventListener('click',async()=>{const s=await miro.board.getSelection();if(!Array.isArray(s)||s.length!==1||!s[0]||s[0].type!=='frame')return alert('Select exactly one frame first.');document.getElementById('frameId').value=String(s[0].id||'');document.getElementById('frameDiagnostic').style.display='block'});
})();`;
  return text(script, 'application/javascript; charset=utf-8');
}
