import { config } from './config.js';
import { text } from './auth.js';

const sdk = '<script src="https://miro.com/app/static/sdk/v2/miro.js"></script>';

export function renderApp() {
  return text(`<!doctype html><html><head><meta charset="utf-8"><title>Jira to Miro position sync</title>${sdk}</head><body><script src="/app.js?v=1"></script></body></html>`, 'text/html; charset=utf-8');
}

export function renderPanel() {
  return text(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Convert Miro notes to Jira</title>${sdk}<style>*{box-sizing:border-box}body{margin:0;padding:20px;font-family:Arial,sans-serif;color:#1a1a1a}h2{margin:0 0 8px;font-size:20px}p{margin:0 0 16px;font-size:13px;line-height:1.45}.card{border:1px solid #e6e6e6;border-radius:8px;padding:16px}button{width:100%;min-height:42px;border:0;border-radius:6px;padding:10px 14px;font-size:14px;font-weight:600;cursor:pointer;background:#4262ff;color:#fff}button:disabled{opacity:.5;cursor:default}#status{display:none;margin-top:14px;padding:10px;border-radius:6px;font-size:12px;line-height:1.4;white-space:pre-wrap}#status.info{display:block;background:#eef2ff}#status.success{display:block;background:#e8f7ed}#status.error{display:block;background:#ffeceb}details{margin-top:14px}summary{cursor:pointer;font-size:12px;color:#666}.admin-tools{margin-top:10px;display:grid;gap:8px}.admin-tools button{background:#fff;color:#4262ff;border:1px solid #4262ff}.diagnostic{display:none;padding:10px;border:1px solid #d9d9d9;border-radius:4px;background:#f7f7f7}.diagnostic input{width:100%;padding:7px}</style></head><body><h2>Convert Miro notes to Jira</h2><p>Select one or more sticky notes. Each note is replaced by a Jira card in exactly the same position. Notes inside a workflow column get that Jira status; notes outside the workflow board keep Jira's default status.</p><div class="card"><button id="convertButton">Convert selected notes</button><div id="status"></div><details><summary>Admin tools</summary><div class="admin-tools"><button id="creatorIdButton" type="button">Show selected item creator ID</button><div id="creatorDiagnostic" class="diagnostic"><label>Miro creator ID</label><input id="creatorId" readonly></div><button id="frameIdButton" type="button">Show selected frame ID</button><div id="frameDiagnostic" class="diagnostic"><label>Miro frame ID</label><input id="frameId" readonly></div></div></details></div><script src="/panel.js?v=1"></script></body></html>`, 'text/html; charset=utf-8');
}

export function renderAppClient(env) {
  const cfg = config(env);
  const script = String.raw`(async function(){
const layout=${JSON.stringify(cfg.layout)}, threshold=${cfg.overlapThreshold};
const timers=new Map(), baselines=new Map(), rollbacks=new Map(), nativeKnown=new Map(), customKnown=new Map();
const norm=v=>String(v||'').trim().toUpperCase();
const nativeKey=item=>{const f=(item.fields||[]).find(x=>/^${cfg.jiraProjectKey}-\d+$/i.test(String(x&&x.value||'').trim()));return f?norm(f.value):null};
const customKey=item=>{const title=String(item&&((item.data&&item.data.title)||item.title)||'').trim();const m=title.match(/^CUSTOM_JIRA_CARD:(${cfg.jiraProjectKey}-\d+)$/i);return m?norm(m[1]):null};
const keyOf=item=>item&&item.type==='card'?nativeKey(item):item&&item.type==='image'?customKey(item):null;
const remember=item=>{if(item&&Number.isFinite(item.x)&&Number.isFinite(item.y))baselines.set(String(item.id),{x:item.x,y:item.y})};
const column=item=>{if(!Number.isFinite(item.x)||!Number.isFinite(item.y)||item.x<layout.board.left||item.x>layout.board.right||item.y<layout.board.top||item.y>layout.board.bottom)return null;const w=Number(item.width)||1,l=item.x-w/2,r=item.x+w/2;return layout.columns.map(c=>({...c,ratio:Math.max(0,Math.min(r,c.right)-Math.max(l,c.left))/w})).sort((a,b)=>b.ratio-a.ratio)[0]};
async function post(path,body){const token=await miro.board.getIdToken();return fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)})}
async function register(){const info=await miro.board.getInfo();const cards=await miro.board.get({type:'card'});const native=[];for(const card of cards||[]){remember(card);const k=nativeKey(card);if(k&&nativeKnown.get(k)!==String(card.id)){native.push({issueKey:k,itemId:String(card.id)});nativeKnown.set(k,String(card.id))}}if(native.length)await post('/register-cards',{boardId:info.id,cards:native});const images=await miro.board.get({type:'image'});const custom=[];for(const image of images||[]){remember(image);const k=customKey(image);if(k&&customKnown.get(k)!==String(image.id)){custom.push({issueKey:k,itemId:String(image.id)});customKnown.set(k,String(image.id))}}if(custom.length)await post('/register-custom-cards',{boardId:info.id,cards:custom})}
async function rollback(item,original){if(!original)return false;try{const current=await miro.board.getById(String(item.id));if(!current)return false;rollbacks.set(String(item.id),Date.now()+5000);current.x=original.x;current.y=original.y;await current.sync();baselines.set(String(item.id),original);return true}catch(e){console.error('Rollback failed',e);return false}}
async function evaluate(id,original){const first=await miro.board.getById(id);if(!first)return;const key=keyOf(first);if(!key){remember(first);return}if(!original){remember(first);return}if(Math.abs(first.x-original.x)<=1&&Math.abs(first.y-original.y)<=1){remember(first);return}await new Promise(r=>setTimeout(r,300));const item=await miro.board.getById(id);if(!item)return;if(Math.abs(item.x-first.x)>1||Math.abs(item.y-first.y)>1)return;const target=column(item);if(!target||target.ratio<threshold){remember(item);return}const info=await miro.board.getInfo();const path=item.type==='card'?'/miro-to-jira':'/custom-miro-to-jira';const body=item.type==='card'?{boardId:info.id,issueKey:key,itemId:id,desiredStatus:target.status}:{boardId:info.id,issueKey:key,groupId:id,desiredStatus:target.status};let response,result;try{response=await post(path,body);result=await response.json()}catch(e){console.error('Status sync failed',e);return}if(!response.ok||result&&result.ok===false){const ok=await rollback(item,original);const message=result&&result.reason==='TEST_AREA_REQUIRED'?'Test area must be filled in before moving to Functional review.':key+' could not be moved to '+target.status+'. Jira rejected the status change.'+(ok?'':' Miro rollback also failed.');try{await miro.board.notifications.showError(message)}catch{}return}remember(item)}
await miro.board.ui.on('icon:click',async()=>{try{await register();if(await miro.board.ui.canOpenPanel())await miro.board.ui.openPanel({url:'/miro-panel'})}catch(e){console.error(e)}});
await miro.board.ui.on('experimental:items:update',event=>{for(const item of event&&event.items||[]){if(item.type!=='card'&&item.type!=='image')continue;const id=String(item.id),until=rollbacks.get(id)||0;if(until>Date.now()){rollbacks.delete(id);remember(item);continue}const old=timers.get(id);if(old)clearTimeout(old.timer);const original=old&&old.original||baselines.get(id)||{x:item.x,y:item.y};const timer=setTimeout(()=>{timers.delete(id);evaluate(id,original).catch(console.error)},1400);timers.set(id,{timer,original})}});
await register();setInterval(()=>register().catch(console.error),10000);
console.log('Jira/Miro sync app ready');
})();`;
  return text(script, 'application/javascript; charset=utf-8');
}

export function renderPanelClient(env) {
  const cfg = config(env);
  const script = String.raw`(function(){
const META='rendraStickyJiraConversionV1',layout=${JSON.stringify(cfg.layout)},threshold=${cfg.overlapThreshold};
const colorMap={light_pink:'Bug',pink:'Bug',violet:'Bug',light_blue:'Improvement',blue:'Improvement',dark_blue:'Improvement',gray:'Improvement',light_yellow:'Spike',yellow:'Spike',light_green:'New Feature',green:'New Feature',dark_green:'New Feature',orange:'Hotfix candidate',red:'Hotfix candidate',cyan:'Task/config/doc/test'};
const button=document.getElementById('convertButton'),statusEl=document.getElementById('status');
const status=(m,t='info')=>{statusEl.className=t;statusEl.textContent=m};
const plain=v=>{const d=document.createElement('div');d.innerHTML=String(v||'');return String(d.textContent||'').replace(/\s+/g,' ').trim()};
const creator=v=>!v?'':typeof v==='string'||typeof v==='number'?String(v).trim():String(v.id||v.userId||v.memberId||v.user&&v.user.id||'').trim();
async function post(path,body){const token=await miro.board.getIdToken();return fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)})}
async function canvas(item){const x=Number(item&&item.x),y=Number(item&&item.y);if(!Number.isFinite(x)||!Number.isFinite(y))throw new Error('A selected note has an invalid board position.');if(!item.parentId||item.relativeTo==='canvas_center')return{x,y};const parent=await miro.board.getById(item.parentId);if(!parent)throw new Error("Could not resolve a selected note's parent frame.");const p=await canvas(parent);if(item.relativeTo==='parent_top_left'){const w=Number(parent.width),h=Number(parent.height);if(!Number.isFinite(w)||!Number.isFinite(h))throw new Error("Could not resolve a selected note's frame dimensions.");return{x:p.x-w/2+x,y:p.y-h/2+y}}if(item.relativeTo==='parent_center')return{x:p.x+x,y:p.y+y};return{x,y}}
function desired(sticky,pos){if(pos.x<layout.board.left||pos.x>layout.board.right||pos.y<layout.board.top||pos.y>layout.board.bottom)return null;const w=Number(sticky.width)||1,l=pos.x-w/2,r=pos.x+w/2;const best=layout.columns.map(c=>({status:c.status,ratio:Math.max(0,Math.min(r,c.right)-Math.max(l,c.left))/w})).sort((a,b)=>b.ratio-a.ratio)[0];return best&&best.ratio>=threshold?best.status:null}
async function jsonResult(response,fallback){let result=null;try{result=await response.json()}catch{}if(!response.ok||!result||!result.ok)throw new Error(typeof(result&&(result.reason||result.error))==='string'?(result.reason||result.error):fallback);return result}
async function convert(sticky){const summary=plain(sticky.content);if(!summary)throw new Error('This sticky note has no text.');const pos=await canvas(sticky),want=desired(sticky,pos),workType=colorMap[String(sticky&&sticky.style&&sticky.style.fillColor||'').trim().toLowerCase()]||'Bug',stickyColor=String(sticky&&sticky.style&&sticky.style.fillColor||'');let state;try{state=await sticky.getMetadata(META)}catch{}let issueKey=state&&state.issueKey?String(state.issueKey):'';if(!issueKey){const created=await jsonResult(await post('/sticky-to-jira',{summary,workType,stickyId:String(sticky.id),createdBy:creator(sticky.createdBy)}),'Could not create Jira issue.');issueKey=String(created.issueKey);await sticky.setMetadata(META,{issueKey,stage:'jira-created',workType,stickyColor,desiredStatus:want||null})}const card=await jsonResult(await post('/conversion-direct-card',{issueKey,x:pos.x,y:pos.y}),'Could not create Miro card at the note position.');if(want)await jsonResult(await post('/conversion-set-status',{issueKey,desiredStatus:want}),'Could not set Jira status.');await sticky.setMetadata(META,{issueKey,stage:'card-created',customCardFrameId:String(card.itemId),workType,stickyColor,desiredStatus:want||null});await miro.board.remove(sticky);return{issueKey,desiredStatus:want}}
button.addEventListener('click',async()=>{button.disabled=true;try{const selected=await miro.board.getSelection(),items=Array.isArray(selected)?selected:[],stickies=items.filter(i=>i&&i.type==='sticky_note');if(!stickies.length)throw new Error('Select at least one sticky note first.');if(stickies.length!==items.length)throw new Error('Select only sticky notes before converting.');const ok=[],fail=[];for(let i=0;i<stickies.length;i++){status('Converting '+(i+1)+' of '+stickies.length+'...');try{ok.push(await convert(stickies[i]))}catch(e){fail.push({text:plain(stickies[i].content).slice(0,60)||'Untitled note',reason:e&&e.message||String(e)})}}if(!fail.length)status(ok.length===1?ok[0].issueKey+' converted successfully.':ok.length+' notes converted successfully.','success');else if(ok.length)status(ok.length+' converted successfully. '+fail.length+' failed and were left on the board.\n\n'+fail.map(x=>x.text+': '+x.reason).join('\n'),'error');else status('No notes were converted.\n\n'+fail.map(x=>x.text+': '+x.reason).join('\n'),'error')}catch(e){status(e&&e.message||String(e),'error')}finally{button.disabled=false}});
document.getElementById('creatorIdButton').addEventListener('click',async()=>{const s=await miro.board.getSelection();if(!Array.isArray(s)||s.length!==1)return alert('Select exactly one item first.');const value=creator(s[0].createdBy);if(!value)return alert('Could not read creator ID for the selected item.');document.getElementById('creatorId').value=value;document.getElementById('creatorDiagnostic').style.display='block'});
document.getElementById('frameIdButton').addEventListener('click',async()=>{const s=await miro.board.getSelection();if(!Array.isArray(s)||s.length!==1||!s[0]||s[0].type!=='frame')return alert('Select exactly one frame first.');document.getElementById('frameId').value=String(s[0].id||'');document.getElementById('frameDiagnostic').style.display='block'});
})();`;
  return text(script, 'application/javascript; charset=utf-8');
}