import { renderAppClient } from './app-client.js';
import { renderPanelClient } from './panel-client.js';

const sdk = '<script src="https://miro.com/app/static/sdk/v2/miro.js"></script>';

export function renderApp() {
  return text(`<!doctype html><html><head><meta charset="utf-8"><title>Jira to Miro position sync</title>${sdk}</head><body><script src="/app.js?v=13"></script></body></html>`, 'text/html; charset=utf-8');
}

export function renderPanel() {
  return text(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Convert Miro notes to Jira</title>${sdk}<style>*{box-sizing:border-box}body{margin:0;padding:20px;font-family:Arial,sans-serif;color:#1a1a1a}h2{margin:0 0 8px;font-size:20px}p{margin:0 0 16px;font-size:13px;line-height:1.45}.card{border:1px solid #e6e6e6;border-radius:8px;padding:16px}button{width:100%;min-height:42px;border:0;border-radius:6px;padding:10px 14px;font-size:14px;font-weight:600;cursor:pointer;background:#4262ff;color:#fff}button:disabled{opacity:.5;cursor:default}#status{display:none;margin-top:14px;padding:10px;border-radius:6px;font-size:12px;line-height:1.4;white-space:pre-wrap}#status.info{display:block;background:#eef2ff}#status.success{display:block;background:#e8f7ed}#status.error{display:block;background:#ffeceb}details{margin-top:14px}summary{cursor:pointer;font-size:12px;color:#666}.admin-tools{margin-top:10px;display:grid;gap:8px}.admin-tools button{background:#fff;color:#4262ff;border:1px solid #4262ff}.diagnostic{display:none;padding:10px;border:1px solid #d9d9d9;border-radius:4px;background:#f7f7f7}.diagnostic input{width:100%;padding:7px}</style></head><body><h2>Convert Miro notes to Jira</h2><p>Select one or more sticky notes. Each note creates a Jira issue and is replaced by a custom card in the same position. Notes inside a workflow column get that Jira status; notes outside the workflow board keep Jira's default status.</p><div class="card"><button id="convertButton">Convert selected notes</button><div id="status"></div><details><summary>Admin tools</summary><div class="admin-tools"><button id="creatorIdButton" type="button">Show selected item creator ID</button><div id="creatorDiagnostic" class="diagnostic"><label>Miro creator ID</label><input id="creatorId" readonly></div><button id="frameIdButton" type="button">Show selected frame ID</button><div id="frameDiagnostic" class="diagnostic"><label>Miro frame ID</label><input id="frameId" readonly></div></div></details></div><script src="/panel.js?v=3"></script></body></html>`, 'text/html; charset=utf-8');
}